# Generated by Django 4.2.16 on 2024-11-24 11:59

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='InfoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_after', models.DateTimeField(verbose_name='Zobrazuj od')),
                ('visible_until', models.DateTimeField(verbose_name='Zobrazuj do')),
                ('message', models.CharField(help_text='Správa sa zobrazí v baneri. Správa musí byť stručná - jedna krátka veta.', max_length=200, verbose_name='správa')),
            ],
            options={
                'verbose_name': 'Informácia v pohyblivom baneri',
                'verbose_name_plural': 'Informácie v pohyblivom baneri',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='názov loga')),
                ('disabled', models.BooleanField()),
                ('image', base.models.RestrictedFileField(upload_to='logo_images/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logá',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pomenovanie generickej správy. Slúži pre orientáciu', max_length=50, verbose_name='Názov')),
                ('message', models.CharField(help_text='Generické správy pre banner a posty', max_length=200, verbose_name='Generická správa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktívna')),
            ],
            options={
                'verbose_name': 'Generické správy pre banner a posty',
                'verbose_name_plural': 'Generické správy pre banner a posty',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_after', models.DateTimeField(verbose_name='Zobrazuj od')),
                ('visible_until', models.DateTimeField(verbose_name='Zobrazuj do')),
                ('caption', models.CharField(max_length=50, verbose_name='nadpis')),
                ('short_text', models.CharField(help_text='Krátky 1-2 vetový popis.', max_length=200, verbose_name='krátky text')),
                ('details', models.TextField(blank=True, help_text='Dlhší text, ktorý sa zobrazí po rozkliknutí.', verbose_name='podrobnosti k príspevku')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='pridané')),
                ('sites', models.ManyToManyField(to='base.site')),
            ],
            options={
                'verbose_name': 'príspevok',
                'verbose_name_plural': 'príspevky',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Nápis, ktorý po kliknutí presmeruje na link. Maximálne 2 slová.', max_length=25, verbose_name='názov')),
                ('url', models.CharField(help_text='URL stránky kam má preklik viesť', max_length=100, verbose_name='URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.post', verbose_name='Relevantný príspevok')),
            ],
            options={
                'verbose_name': 'link k príspevku',
                'verbose_name_plural': 'linky k príspevkom',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(help_text='Nápis, ktorý sa zobrazí v menu. Maximálne 2 slová.', max_length=25, verbose_name='názov')),
                ('url', models.TextField(help_text='URL stránky kam má preklik viesť', verbose_name='URL')),
                ('priority', models.SmallIntegerField(help_text='Priorita, čím väčšie, tým vyššie v menu.', verbose_name='priorita')),
                ('in_footer', models.BooleanField(default=False, verbose_name='Je v pätičke')),
                ('in_menu', models.BooleanField(default=True, verbose_name='Je v menu')),
                ('sites', models.ManyToManyField(to='base.site')),
            ],
            options={
                'verbose_name': 'položka v menu',
                'verbose_name_plural': 'položky v menu',
                'ordering': ['-priority'],
            },
        ),
    ]
