# Generated by Django 4.2.13 on 2024-06-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
        ('competition', '0001_initial'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobanner',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.event'),
        ),
        migrations.AddField(
            model_name='infobanner',
            name='message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cms.messagetemplate'),
        ),
        migrations.AddField(
            model_name='infobanner',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flatpages.flatpage'),
        ),
        migrations.AddField(
            model_name='infobanner',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.series'),
        ),
    ]
