# Generated by Django 5.2.2 on 2025-12-06 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
        ('competition', '0007_competition_default_sum_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='názov galérie')),
                ('gallery_link', models.URLField(help_text='Odkaz na externú galériu (napr. Google Photos)', verbose_name='odkaz na galériu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvorené')),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='competition.event', verbose_name='súťaž')),
            ],
            options={
                'verbose_name': 'galéria',
                'verbose_name_plural': 'galérie',
            },
        ),
    ]
