# Generated by Django 4.2.15 on 2024-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.TextField(help_text='URL stránky kam má preklik viesť', verbose_name='URL'),
        ),
    ]
