# Generated by Django 5.2.2 on 2025-12-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_gallery'),
        ('competition', '0007_competition_default_sum_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='competition.event', verbose_name='súťaž'),
        ),
    ]
