# Generated by Django 5.2.2 on 2026-04-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_gallery_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='url',
            field=models.TextField(blank=True, help_text='URL stránky kam má logo po kliknutí viesť', null=True, verbose_name='URL'),
        ),
    ]
