# Generated by Django 4.2.11 on 2024-04-14 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='dátum')),
                ('description', models.TextField(verbose_name='popis')),
                ('soft_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'aktivita',
                'verbose_name_plural': 'aktivity',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='názov')),
            ],
            options={
                'verbose_name': 'typ aktivity',
                'verbose_name_plural': 'typy aktivít',
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='názov')),
                ('activity_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.activitytype', verbose_name='typ aktivity')),
            ],
            options={
                'verbose_name': 'náročnosť',
                'verbose_name_plural': 'náročnosti',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(verbose_name='príklad')),
                ('result', models.CharField(max_length=128, verbose_name='výsledok')),
                ('solution', models.TextField(verbose_name='riešenie')),
                ('soft_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'príklad',
                'verbose_name_plural': 'príklady',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='názov seminára')),
            ],
            options={
                'verbose_name': 'seminár',
                'verbose_name_plural': 'semináre',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='názov tagu')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tagy',
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='názov')),
                ('description', models.TextField(verbose_name='popis')),
                ('seminar', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.seminar', verbose_name='seminár')),
            ],
            options={
                'verbose_name': 'typ príkladu',
                'verbose_name_plural': 'typy príkladov',
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.problem', verbose_name='príklad')),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.tag', verbose_name='aktivita')),
            ],
            options={
                'verbose_name': 'priradenie príkladu k tagu',
                'verbose_name_plural': 'priradenia príkladov k tagom',
            },
        ),
        migrations.CreateModel(
            name='ProblemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.activity', verbose_name='aktivita')),
                ('difficulty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.difficulty', verbose_name='náročnosť')),
                ('problem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.problem', verbose_name='príklad')),
            ],
            options={
                'verbose_name': 'priradenie problému k aktivite/obtiežnosti',
                'verbose_name_plural': 'priradenie problémov k aktivitám/obtiažnostiam',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.ManyToManyField(to='problem_database.problemtype'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='', verbose_name='priložené súbory')),
                ('soft_deleted', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.problem', verbose_name='príklad')),
            ],
            options={
                'verbose_name': 'súbor',
                'verbose_name_plural': 'súbory',
            },
        ),
        migrations.AddField(
            model_name='activitytype',
            name='seminar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.seminar', verbose_name='seminár'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem_database.activitytype', verbose_name='typ aktivity'),
        ),
    ]
