# Generated by Django 4.2.13 on 2024-06-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='county',
            field=models.ForeignKey(on_delete=models.SET(personal.models.unspecified_county), to='personal.county', verbose_name='kraj'),
        ),
    ]
