# Generated by Django 4.2.15 on 2025-06-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSchoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_info', models.TextField(verbose_name='Požadovaná škola na pridanie')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_school_request', to='personal.profile')),
            ],
        ),
    ]
