# Generated by Django 5.2.2 on 2025-12-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_school_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherschoolrequest',
            options={'verbose_name': 'Požiadavok na založenie školy', 'verbose_name_plural': 'Požiadavky na založenie školy'},
        ),
    ]
