# Generated by Django 4.2.13 on 2024-06-10 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_initial'),
        ('competition', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcorrection',
            name='corrected_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='opravovatelia'),
        ),
        migrations.AddField(
            model_name='problemcorrection',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='competition.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='competition.series', verbose_name='úloha zaradená do série'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.event', verbose_name='semester'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.grade', verbose_name='ročník'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.profile', verbose_name='profil'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.school', verbose_name='škola'),
        ),
        migrations.AddField(
            model_name='event',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.registrationlink'),
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.competitiontype', verbose_name='typ súťaže'),
        ),
        migrations.AddField(
            model_name='competition',
            name='permission_group',
            field=models.ManyToManyField(blank=True, related_name='competition_permissions', to='auth.group', verbose_name='Skupiny práv'),
        ),
        migrations.AddField(
            model_name='competition',
            name='sites',
            field=models.ManyToManyField(to='sites.site'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor komentára'),
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.problem', verbose_name='komentár k úlohe'),
        ),
        migrations.AddField(
            model_name='series',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.semester', verbose_name='semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='late_tags',
            field=models.ManyToManyField(blank=True, to='competition.latetag', verbose_name='Stavy omeškania'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('profile', 'event'), name='single_registration_in_event'),
        ),
    ]
