# Generated by Django 4.2.15 on 2024-11-23 19:43

import base.models
import competition.models
import django.core.files.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='corrected_solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='C:\\Users\\petko\\Documents\\GitHub\\webstrom\\webstrom-backend\\protected_media/'), upload_to=competition.models.get_corrected_solution_path, verbose_name='opravené riešenie'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='C:\\Users\\petko\\Documents\\GitHub\\webstrom\\webstrom-backend\\protected_media/'), upload_to=competition.models.get_solution_path, verbose_name='účastnícke riešenie'),
        ),
    ]
