# Generated by Django 4.2.15 on 2025-05-24 21:16

import base.models
import competition.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0003_alter_series_options_alter_publication_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='from_staff',
            field=models.BooleanField(default=False, verbose_name='Komentár od vedúceho'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='autor komentára'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='corrected_solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='C:\\Users\\petko\\Documents\\GitHub\\webstrom\\webstrom-backend\\protected_media/'), upload_to=competition.models.get_corrected_solution_path, verbose_name='opravené riešenie'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='C:\\Users\\petko\\Documents\\GitHub\\webstrom\\webstrom-backend\\protected_media/'), upload_to=competition.models.get_solution_path, verbose_name='účastnícke riešenie'),
        ),
    ]
