# Generated by Django 4.2.16 on 2024-11-23 22:54

import base.models
import competition.models
import django.core.files.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_solution_corrected_solution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemcorrection',
            options={'verbose_name': 'Opravenie úlohy', 'verbose_name_plural': 'Opravené úlohy'},
        ),
        migrations.AlterField(
            model_name='solution',
            name='corrected_solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='/home/mihal/Documents/STROM/webstrom/webstrom-backend/protected_media/'), upload_to=competition.models.get_corrected_solution_path, verbose_name='opravené riešenie'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='/home/mihal/Documents/STROM/webstrom/webstrom-backend/protected_media/'), upload_to=competition.models.get_solution_path, verbose_name='účastnícke riešenie'),
        ),
    ]
