# Generated by Django 4.2.15 on 2025-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_comment_from_staff_alter_comment_posted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='alert_email',
            field=models.EmailField(blank=True, default=None, max_length=254,
                                    null=True, verbose_name='Email pre upozornenia z diskusií'),
        ),
    ]
