# Generated by Django 4.2.15 on 2025-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competition_alert_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis súťaže'),
        ),
    ]
