# Generated by Django 5.2.2 on 2025-12-05 23:37

import base.models
import competition.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competition_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='default_sum_method',
            field=models.CharField(blank=True, choices=[('series_simple_sum', 'Jednoduchý súčet bodov'), ('series_Malynar_sum', 'Bonifikácia Malynár'), ('series_Matik_sum', 'Bonifikácia Matik'), ('series_STROM_sum', 'Bonifikácia STROM'), ('series_Malynar_sum_until_2021', 'Bonifikácia Malynár (Do 2020/2021)'), ('series_Matik_sum_until_2021', 'Bonifikácia Matik (Do 2020/2021)'), ('series_STROM_sum_until_2021', 'Bonifikácia STROM (Do 2020/2021)'), ('series_STROM_4problems_sum', 'Bonifikácia STROM (4. úlohy)')], default='series_simple_sum', max_length=50, verbose_name='Súčtová metóda'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='corrected_solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='C:\\Users\\petko\\Projects\\webstrom-backend\\protected_media/'), upload_to=competition.models.get_corrected_solution_path, verbose_name='opravené riešenie'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution',
            field=base.models.RestrictedFileField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected/', location='C:\\Users\\petko\\Projects\\webstrom-backend\\protected_media/'), upload_to=competition.models.get_solution_path, verbose_name='účastnícke riešenie'),
        ),
    ]
